# Generated by Django 5.1.4 on 2025-04-16 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_loginlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginLog',
        ),
    ]
