# Generated by Django 5.2.4 on 2025-07-18 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
