# Generated by Django 5.1.4 on 2025-07-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_profile_travelphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='travel_photo',
            field=models.ImageField(blank=True, null=True, upload_to='travel_photos/'),
        ),
    ]
