# Generated by Django 5.1.4 on 2025-07-23 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_profile_travel_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelphoto',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='TravelPhoto',
        ),
    ]
